name: QuizBlock
main: QuizBlock.QuizBlock
version: 0.6.0
author: Codisimus
website: www.codisimus.com
description: Door opens when correct block is broken
commands:
  quizblock:
    alias: qb
    description: Main command, type for additional help/commands